


<TEST_SCRIPT>
H
E
L
L
O

</TEST_SCRIPT>
<TEST_SCRIPT>
HELLO WAIT 5 SECONDS{SUSPEND(05000)}
I HAVE A MESSAGE FOR YOU{SUSPEND(05000)}{BACKSPACE}{BACKSPACE}{BACKSPACE}{BACKSPACE}{BACKSPACE}{BACKSPACE}{BACKSPACE}{BACKSPACE}{BACKSPACE}{BACKSPACE}{BACKSPACE}{BACKSPACE}{BACKSPACE}{BACKSPACE}{BACKSPACE}{BACKSPACE}{BACKSPACE}{BACKSPACE}{SUSPEND(02000)}.{SUSPEND(02000)}..{SUSPEND(02000)}.{TAB}NOTHING FOR YOU HEHE...BYE.
</TEST_SCRIPT>